env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  semi:
    - 'error'
    - 'always'
  quotes:
    - 'error'
    - 'single'
parser: "@babel/eslint-parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2020
  babelOptions:
    plugins:
      - "@babel/plugin-syntax-import-assertions"
